services:
  db:
    image: ${DB_FLAVOR}:${DB_VERSION}
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: ${DB_TIMEZONE}
    command:
      - --character-set-server=${DB_CHARSET}
      - --collation-server=${DB_COLLATION}
      - --default-authentication-plugin=${DB_AUTH_PLUGIN}
      - --lower_case_table_names=${DB_LOWER_CASE_TABLE_NAMES}
      - --sql_mode=${DB_SQL_MODE}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build:
      context: ./web
      args:
        PHP_VERSION: ${PHP_VERSION}
        APACHE_DOCUMENT_ROOT: ${APACHE_DOCUMENT_ROOT}
    environment:
      - DOCKER_CONTAINER=true
    volumes:
      - ./:/var/www/html
      - ./web/vhost.conf:/etc/apache2/sites-available/000-default.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: db
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  db_data:
